# Generated by Django 3.2 on 2021-04-26 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_inicial', models.IntegerField()),
                ('posicao_final', models.IntegerField()),
                ('destaque', models.TextField()),
                ('data', models.DateTimeField()),
                ('nota', models.TextField()),
                ('book', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='notes.book')),
            ],
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
